
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/talk
    username: postgres
    password: aegisep1234@
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: false #??? job
    jdbc:
      initialize-schema: never # ??? ????
server:
  port: 9000
